services:
  - type: web
    name: crm
    runtime: python
    buildCommand: bash build.sh
    startCommand: python -m gunicorn crm.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
