# Generated by Django 6.0.5 on 2026-05-06 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('niche', models.CharField(blank=True, help_text='Example: Roofing, HVAC, Plumbing', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Example: OC, Anaheim, Los Angeles', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(default='Roofing', max_length=100)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 - Hot'), (2, 'Tier 2 - Warm'), (3, 'Tier 3 - Skip')], default=2)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('NO_ANSWER', 'No Answer'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('DEMO_BOOKED', 'Demo Booked'), ('CLOSED', 'Closed'), ('NOT_QUALIFIED', 'Not Qualified')], default='NEW', max_length=30)),
                ('hook', models.TextField(blank=True)),
                ('warning', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('COPIED', 'Copied'), ('SENT', 'Sent')], default='GENERATED', max_length=20)),
                ('provider', models.CharField(choices=[('TEMPLATE', 'Template'), ('ANTHROPIC', 'Anthropic'), ('OPENAI', 'OpenAI')], default='TEMPLATE', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LEAD_IMPORTED', 'Lead Imported'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('NOTE_ADDED', 'Note Added'), ('CALL_LOGGED', 'Call Logged'), ('EMAIL_GENERATED', 'Email Generated'), ('EMAIL_SENT', 'Email Sent'), ('STATUS_CHANGED', 'Status Changed')], max_length=40)),
                ('outcome', models.CharField(blank=True, choices=[('NEW', 'New'), ('NO_ANSWER', 'No Answer'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('DEMO_BOOKED', 'Demo Booked'), ('CLOSED', 'Closed'), ('NOT_QUALIFIED', 'Not Qualified')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('NEW', 'New'), ('NO_ANSWER', 'No Answer'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('DEMO_BOOKED', 'Demo Booked'), ('CLOSED', 'Closed'), ('NOT_QUALIFIED', 'Not Qualified')], max_length=30)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='core_lead_status_7318b1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tier'], name='core_lead_tier_97c0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='core_lead_assigne_1528df_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email_sent'], name='core_lead_email_s_fef700_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['business_type'], name='core_lead_busines_16beb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('campaign', 'phone'), name='unique_lead_phone_per_campaign'),
        ),
    ]
