# Generated by Django 6.0.5 on 2026-05-06 20:50

from django.conf import settings
from django.db import migrations, models


def backfill_phone_called(apps, schema_editor):
    lead = apps.get_model("core", "Lead")
    lead.objects.filter(last_contacted_at__isnull=False).update(
        phone_called=True,
        phone_called_at=models.F("last_contacted_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_phone_called, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_called'], name='core_lead_phone_c_84ba48_idx'),
        ),
    ]
