# Generated by Django 6.0.5 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lead_phone_called_lead_phone_called_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="core_lead_email_40e23f_idx"),
        ),
        migrations.AddField(
            model_name="leadnote",
            name="channel",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("PHONE", "Phone"),
                    ("EMAIL", "Email"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="leadnote",
            index=models.Index(fields=["channel"], name="core_leadno_channel_3d452a_idx"),
        ),
    ]
