# Generated by Django 6.0.5 on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_agentphonenumber_usage_count_and_more"),
        ("core", "0003_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadnote",
            name="phone_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_notes",
                to="accounts.agentphonenumber",
            ),
        ),
    ]
