# Generated by Django 6.0.5 on 2026-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_num_of_reviews_lead_state_lead_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
