# Generated by Django 6.0.5 on 2026-05-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentphonenumber',
            name='unique_phone_per_agent',
        ),
        migrations.AlterField(
            model_name='agentphonenumber',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agentphonenumber',
            constraint=models.UniqueConstraint(fields=('phone',), name='unique_agent_phone_number'),
        ),
    ]
