# Generated by Django 6.0.5 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_agentphonenumber_unique_phone_per_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentphonenumber",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentphonenumber",
            name="usage_limit",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
